export const FETCHPRODUCTSSTART = 'FETCH_PRODUCTS_START'
export const FETCHPRODUCTSSUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCHPRODUCTFAILED = 'FETCH_PRODUCTS_FAILED'

export const ADDCOUNT = 'ADD_COUNT'
export const MINUSCOUNT = 'MINUS_COUNT'

export const FETCHDETAILSTART = 'FETCH_DETAIL_START'
export const FETCHDETAILFAILED = 'FETCH_DETAIL_FAILED'
export const FETCHDETAILSUCCESS = 'FETCH_DETAIL_SUCCESS'
